apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: my-react-app
spec:
  releaseName: my-react-app
  chart:
    repository: https://charts.example.com/stable
    name: my-react-app
    version: 1.0.0
  values:
    replicaCount: 1
    image:
      repository: mohamedamine1/frontend
      tag: frontend-pfe
      pullPolicy: IfNotPresent
    service:
      type: LoadBalancer
      port: 3000
