apiVersion: v1
kind: Service
metadata:
  name: my-nest-app-service
spec:
  selector:
    app: my-nest-app
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP  # Added protocol for clarity

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP  # Added protocol for clarity

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP  # Added protocol for clarity

---

apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  selector:
    app: my-react-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP  # Added protocol for clarity