apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nestjs-mongodb-redis-reactjs
spec:
  releaseName: nestjs-mongodb-redis-reactjs # corrected field name
  chart:
    repository: https://charts.example.com/stable
    name: nestjs-mongodb-redis-reactjs # centralized chart name
    version: 1.0.0
  values:
    # Application NestJS
    my-nest-app:
      replicaCount: 3
      image:
        repository: mohamedamine1/backend-azure
        tag: back
        pullPolicy: IfNotPresent
      service:
        type: LoadBalancer
        port: 80
      env:
        MONGO_URI: 'mongodb://amine:Hamidou123@mongodb-service:27017/?retryWrites=true&w=majority&appName=Cluster0'
        REDIS_HOST: redis-service
        REDIS_PORT: '6379'

    # MongoDB
    mongodb:
      replicaCount: 1
      image:
        repository: mongo
        tag: latest
        pullPolicy: IfNotPresent
      env:
        MONGO_INITDB_ROOT_USERNAME: amine
        MONGO_INITDB_ROOT_PASSWORD: Hamidou123
      service:
        type: LoadBalancer
        port: 27017

    # Redis
    redis:
      replicaCount: 1
      image:
        repository: redis
        tag: latest
        pullPolicy: IfNotPresent
      service:
        type: LoadBalancer
        port: 6379

    # React app
    my-react-app:
      replicaCount: 1
      image:
        repository: mohamedamine1/frontend-azure
        tag: front
        pullPolicy: IfNotPresent
      service:
        type: LoadBalancer
        port: 3000
